replicas:
  min: 1
  max: 2
kafka-pool: "nav-dev"
naisEnv: dev
topic: teamdokumenthandtering.aapen-dok-journalfoering
saf:
  url: https://saf.dev-fss-pub.nais.io
  scope: api://dev-fss.teamdokumenthandtering.saf/.default
  outbound: saf.dev-fss-pub.nais.io
