replicas:
  min: 2
  max: 4
kafka-pool: "nav-prod"
sqlInstances:
  diskAutoresize: true
  pointInTimeRecovery: true
  tier: db-custom-1-3840
naisEnv: prod
topic: teamdokumenthandtering.aapen-dok-journalfoering
saf:
  url: https://saf.prod-fss-pub.nais.io
  scope: api://prod-fss.teamdokumenthandtering.saf/.default
  outbound: saf.prod-fss-pub.nais.io
saksbehandlingApi:
  url: http://tiltakspenger-saksbehandling-api
  scope: api://prod-gcp.tpts.tiltakspenger-saksbehandling-api/.default
