replicas:
  min: 2
  max: 4
kafka-pool: "nav-prod"
naisEnv: prod
topic: teamdokumenthandtering.aapen-dok-journalfoering
saf:
  url: https://saf.prod-fss-pub.nais.io
  scope: api://prod-fss.teamdokumenthandtering.saf/.default
  outbound: saf.prod-fss-pub.nais.io
