apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-journalposthendelser
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  replicas:
  {{#with replicas}}
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  {{/with}}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    sqlInstances:
      - name: tiltakspenger-journalposthendelser
        type: POSTGRES_17
        tier: {{ sqlInstances.tier }}
        diskAutoresize: {{ sqlInstances.diskAutoresize }}
        pointInTimeRecovery: {{ sqlInstances.pointInTimeRecovery }}
        databases:
          - name: journalposthendelser
            envVarPrefix: DB
  kafka:
    pool: {{ kafka-pool }}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: tiltakspenger-saksbehandling-api
      external:
       - host: {{ saf.outbound }}
       - host: {{ oppgave.outbound }}
       - host: {{ dokarkiv.outbound }}
  env:
    - name: PORT
      value: "8080"
    - name: LOGBACK_CONFIG_FILE
      value: "logback.xml"
    - name: AAPEN_DOK_JOURNALFOERING_TOPIC
      value: {{ topic }}
    - name: SAF_URL
      value: {{ saf.url }}
    - name: SAF_SCOPE
      value: {{ saf.scope }}
    - name: SAKSBEHANDLING_API_URL
      value: {{ saksbehandlingApi.url }}
    - name: SAKSBEHANDLING_API_SCOPE
      value: {{ saksbehandlingApi.scope }}
    - name: OPPGAVE_URL
      value: {{ oppgave.url }}
    - name: OPPGAVE_SCOPE
      value: {{ oppgave.scope }}
    - name: DOKARKIV_URL
      value: {{ dokarkiv.url }}
    - name: DOKARKIV_SCOPE
      value: {{ dokarkiv.scope }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
