apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-journalposthendelser
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  replicas:
  {{#with replicas}}
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  {{/with}}
  ingresses:
    - {{ ingress.url }}
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka-pool }}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
       - host: {{ saf.url }}
  env:
    - name: PORT
      value: "8080"
    - name: LOGBACK_CONFIG_FILE
      value: "logback.xml"
    - name: AAPEN_DOK_JOURNALFOERING_TOPIC
      value: {{ topic }}
    - name: SAF_URL
      value: {{ saf.url }}
    - name: SAF_SCOPE
      value: {{ saf.scope }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
